services:
    - xvfb
language: node_js
matrix:
  include:
    - node_js: 8
      env: TEST=unit
    - node_js: 11
      env: TEST=unit
    - node_js: 12
      env: TEST=unit
    - node_js: 10
      env: TEST=unit_and_e2e
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-5";
      export CXX="g++-5";
      export LINK="gcc-5";
      export LINKXX="g++-5";
    fi
install:
    - npm install
script:
    - npm run ci

